// micro-viv/src/App.vue
<!--
 * @Author: linqibin
 * @Date: 2022-09-08 09:53:37
 * @LastEditors: linqibin
 * @LastEditTime: 2022-09-09 15:21:00
 * @Description: 
 * 
 * Copyright (c) 2022 by 研发中心/金地楼宇, All Rights Reserved. 
-->
<script setup lang="ts">
// This starter template is using Vue 3 <script setup> SFCs
// Check out https://vuejs.org/api/sfc-script-setup.html#script-setup
import { ref } from 'vue';
const DEV = ref(import.meta.env.MODE === 'development')
</script>

<template>
  <div>
    <a href="https://vitejs.dev" target="_blank">
      <img :src="DEV ? 'http://localhost:5173/vite.svg' : '/vite.svg'" class="logo" alt="Vite logo" />
    </a>
    <a href="https://vuejs.org/" target="_blank">
      <img src="./assets/vue.svg" class="logo vue" alt="Vue logo" />
    </a>
  </div>
  <div>
    <router-link to="/"> 首页 </router-link> |
    <router-link to="/about"> 关于 </router-link>
  </div>
  <router-view />
</template>

<style scoped>
.logo {
  height: 6em;
  padding: 1.5em;
  will-change: filter;
}
.logo:hover {
  filter: drop-shadow(0 0 2em #0b0b0eaa);
}
.logo.vue:hover {
  filter: drop-shadow(0 0 2em #42b883aa);
}
</style>

// micro-vir/src/App.tsx
/*
 * @Author: linqibin
 * @Date: 2022-09-08 14:12:31
 * @LastEditors: linqibin
 * @LastEditTime: 2022-09-09 15:21:27
 * @Description:
 *
 * Copyright (c) 2022 by 研发中心/金地楼宇, All Rights Reserved.
 */
import React, { useState } from "react";
import { BrowserRouter, Routes, Route, Link, Outlet } from "react-router-dom";
import reactLogo from "./assets/react.svg";
import { qiankunWindow } from "vite-plugin-qiankun/dist/helper";
import "./App.css";

function App() {
  const [count, setCount] = useState(0);
  const [DEV] = useState(import.meta.env.MODE === "development");

  return (
    <BrowserRouter
      basename={qiankunWindow.__POWERED_BY_QIANKUN__ ? "/micro-vir" : "/"}
    >
      <Routes>
        <Route
          path="/"
          element={
            <div className="App">
              <div>
                <a href="https://vitejs.dev" target="_blank">
                  <img
                    src={DEV ? "http://localhost:5174/vite.svg" : "/vite.svg"}
                    className="logo"
                    alt="Vite logo"
                  />
                </a>
                <a href="https://reactjs.org" target="_blank">
                  <img
                    src={reactLogo}
                    className="logo react"
                    alt="React logo"
                  />
                </a>
              </div>
              <h1>Vite + React</h1>
              <div className="card">
                <button onClick={() => setCount((count) => count + 1)}>
                  count is {count}
                </button>
                <p>
                  Edit <code>src/App.tsx</code> and save to test HMR
                </p>
              </div>
              <div>
                <Link to="/home">首页666</Link> |<Link to="/user">用户</Link>
              </div>
              <div>
                <Outlet />
              </div>
              <p className="read-the-docs">
                Click on the Vite and React logos to learn more
              </p>
            </div>
          }
        >
          <Route path="/home" element={<div>这是首页</div>} />
          <Route path="/user" element={<div>这是用户中心</div>} />
        </Route>
      </Routes>
    </BrowserRouter>
  );
}

export default App;
